### ISSUE TITLE
IDR_stream CP segmentation differences

### ISSUE THREAD

**Issue by roshankern** [WayScience/IDR_stream#17]
It seems that running `idr_stream_cp.py` can have different segmentation results depending on the batch size.
All tests below were done with negative [control locations metadata](https://github.com/roshankern/IDR_stream/blob/resolve-cp-features-issues/example_notebooks/example_files/data_to_process.tsv).

Screenshot outputs are number of cells CellPose found while segmenting

When running the example notebook with `stream.run_cp_stream(data_to_process, batch_size=1, start_batch=0, batch_nums=[1])`:
![image](https://user-images.githubusercontent.com/105665675/220484831-017574b8-5249-40ce-a8b9-184bfe16c858.png)

When running the example notebook with `stream.run_cp_stream(data_to_process, batch_size=3, start_batch=0, batch_nums=[0])`:
![image](https://user-images.githubusercontent.com/105665675/220485073-56b31a9d-d210-4904-9a8d-8e6fe18b4203.png)

`idr_stream_dp` has the same number of cells for this image no matter the batch size:
![image](https://user-images.githubusercontent.com/105665675/220484970-50b1d9bd-3f25-4105-808e-6b569074842c.png)

So it seems like 251 would be the desired number of cells but this changes for `idr_stream_cp` depending on batch size...

**Comment by roshankern** [comment]
Some more testing...

`stream.run_cp_stream(data_to_process, batch_size=2, start_batch=0, batch_nums=[0])`:
![image](https://user-images.githubusercontent.com/105665675/220485521-bfbbff69-dbe6-4b5b-9277-555b2973f231.png)

`stream.run_cp_stream(data_to_process, batch_size=4, start_batch=0, batch_nums=[0])`:
![image](https://user-images.githubusercontent.com/105665675/220485521-bfbbff69-dbe6-4b5b-9277-555b2973f231.png)

`stream.run_cp_stream(data_to_process, batch_size=5, start_batch=0, batch_nums=[0])`:
![image](https://user-images.githubusercontent.com/105665675/220485521-bfbbff69-dbe6-4b5b-9277-555b2973f231.png)

**Comment by jenna-tomkinson** [comment]
@roshankern 

Can you clarify what the values for `251` and `249` represent as I understand they are the number of single cells, but for what? One image? The whole batch? If it is in one image, can you confirm that this output comes from the same image every time? 

I get this is probably the same image, but for clarity on this issue, it might be good to make it clear that these are the cell counts from the same image between CP and DP.

**Comment by roshankern** [comment]
Yep, as you suggest, these are the same image and `251` and `249` correspond to the number of cells `CellPose` segments for the various runs.

> If it is in one image, can you confirm that this output comes from the same image every time?

These cell counts do indeed come from the same image every time. I will do a little more testing to try and figure out where these differences are occurring but I think the most viable option moving forward would be to make the merge function adapt to significant segmentation differences.

**Comment by roshankern** [comment]
The following are image difference tests to determine if the illumination-corrected frames differ between the CP and DP runs:

`stream.run_cp_stream(data_to_process, batch_size=1, start_batch=0, batch_nums=[1])` and
`stream.run_dp_stream(data_to_process, batch_size=1, start_batch=0, batch_nums=[1])`:
![image](https://user-images.githubusercontent.com/105665675/220800602-341cc1f2-8d83-4317-9282-70fb4c1e4f9b.png)

`stream.run_cp_stream(data_to_process, batch_size=2, start_batch=0, batch_nums=[0])` and `stream.run_dp_stream(data_to_process, batch_size=2, start_batch=0, batch_nums=[0])`:
![image](https://user-images.githubusercontent.com/105665675/220800396-52972717-94c2-4f39-8d7b-9482bd37d63f.png)

`stream.run_cp_stream(data_to_process, batch_size=3, start_batch=0, batch_nums=[0])` and `stream.run_dp_stream(data_to_process, batch_size=3, start_batch=0, batch_nums=[0])`:
![image](https://user-images.githubusercontent.com/105665675/220800036-d0b482cf-9398-4a50-83b1-19ebdfc5ec1e.png)

Clearly, the illumination-corrected images are consistent across the same batch size parameters (indicating the difference originates with CellPose segmentations).

**Comment by jenna-tomkinson** [comment]
@roshankern 

I might have the fix for this in my latest PR #20. I noticed that the `min_size` parameter, though not referenced as a parameter in the DP specs, is defaulted to 15 and not turned off as I had supposed. This could be the reason for the very small differences in segmentation.

Please use that updated pipeline (only one line of that `.cppipe` is changed so there should be no concern for anything not running) to perform the tests you have done in this issue. 

Even if this isn't the solution to this problem, at least this change has to be made so that the two methods have the same exact parameters now.

**Comment by roshankern** [comment]
Thanks @jenna-tomkinson! After more testing, I don't think this would be causing the segmentation differences but it is a good change to make nonetheless. 

After more testing it seems the issues do arise from environment differences...

In `idr_stream_dp` env:
![image](https://user-images.githubusercontent.com/105665675/221025416-8a41f063-5bc8-4f31-83d6-25177843735d.png)

In `idr_stream_cp` env:
![image](https://user-images.githubusercontent.com/105665675/221025615-f0a0f65c-e202-4696-91f8-e01c32439130.png)

**Comment by roshankern** [comment]
Going through the `CellPose` related packages from the [environment file](https://github.com/MouseLand/cellpose/blob/main/environment.yml)

It seems like the environment differ in:
- pyqt and pyqt5-sip (different versions between CP and DP, seems like this is only for GUI)
- torch (not installed on DP, pytorch is installed on DP instead (pytorch not installed on CP only torch))
- tifffile (different versions between CP and DP, this shouldn't be a big issue as I wouldn't think tiffile would be used after the image is loaded)

**Comment by roshankern** [comment]
It would make the most sense that the version of `torch` or `pytorch` changes the segmentations, as both environments have 251 segmentations when the GPU is not used (and `torch` is presumably not used):

![image](https://user-images.githubusercontent.com/105665675/221033602-77905bd7-6e55-44cb-b4b5-8ecbaaa1c410.png)

![image](https://user-images.githubusercontent.com/105665675/221034171-ff3d30e7-cdf0-4948-85b4-ab7b3f7abdbd.png)

**Comment by roshankern** [comment]
After uninstalling `torch` from `idrstream_cp` and installing `pytorch` version `1.11.0` (same as `idrstream_dp`), CellPose seems to have the exact same segmentations in both environments.

![image](https://user-images.githubusercontent.com/105665675/221089612-b6851c01-5c8e-4d6b-8805-7370e0572bb2.png)

![image](https://user-images.githubusercontent.com/105665675/221089711-5a2daaa1-e79c-40d3-a16c-4bdf385832eb.png)

For reference, the `idrstream_cp` env segmentations before these changes had the following values:
![image](https://user-images.githubusercontent.com/105665675/221089876-f1aa4cd5-1292-4dad-a04f-00df21eb610c.png)

**Comment by roshankern** [comment]
This change has been documented in https://github.com/WayScience/IDR_stream/pull/21

**Comment by roshankern** [comment]
It seems this issue is not completely resolved...

CellProfiler seems to load the illumination-corrected images as floats and CellPose segments these float images very close but slightly different than the int images.

**Comment by roshankern** [comment]
Below are the `np.mean(masks)` values for 3 test images from DP after edge masks are removed:
`19.67032441638765`
`11.578639439174108`
`6.11949956984747`

The mean values for the masks with the CellProfiler-loaded in float images are as follows:
`19.670114426385787`
`11.578712826683407`
`6.119431268601191`
Very close but not the same! This difference can sometimes be reflected with a different number of cells...

After converting the float images loaded in by CellProfiler to int with `x_data = (x_data * 255).round().astype(numpy.uint8)` before segmenting the images with CellPose, the mean values for the masks are exactly the same:
`19.67032441638765`
`11.578639439174108`
`6.11949956984747`

**Comment by roshankern** [comment]
Fixed with https://github.com/WayScience/IDR_stream/pull/22
